// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from opencv.djinni

#include "opencv.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class HWOpencv;

namespace djinni_generated {

class Opencv
{
public:
    using CppType = std::shared_ptr<::opencv::Opencv>;
    using CppOptType = std::shared_ptr<::opencv::Opencv>;
    using ObjcType = HWOpencv*;

    using Boxed = Opencv;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

