// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from opencv.djinni

#import <Foundation/Foundation.h>
@class HWOpencv;


@interface HWOpencv : NSObject

+ (nullable HWOpencv *)create;

- (nonnull NSString *)getCanny:(nonnull NSString *)path;

- (nonnull NSString *)getThreshold:(nonnull NSString *)path;

- (nonnull NSString *)getLines:(nonnull NSString *)path;

- (nonnull NSString *)getContours:(nonnull NSString *)path;

- (nonnull NSString *)getSegments:(nonnull NSString *)path;

- (nonnull NSString *)getRoundContours:(nonnull NSString *)path;

@end
