// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from opencv.djinni

#import <Foundation/Foundation.h>
@class HWOpencv;


@interface HWOpencv : NSObject

+ (nullable HWOpencv *)create;

- (nonnull NSString *)getCanny;

- (nonnull NSString *)getThreshold;

- (nonnull NSString *)getLines;

- (nonnull NSString *)getContours;

- (nonnull NSString *)getSegments;

- (nonnull NSString *)getRoundContours;

@end
