// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from opencv.djinni

#pragma once

#include <memory>
#include <string>

namespace opencv {

class Opencv {
public:
    virtual ~Opencv() {}

    static std::shared_ptr<Opencv> create();

    virtual std::string get_canny(const std::string & path) = 0;

    virtual std::string get_threshold(const std::string & path) = 0;

    virtual std::string get_lines(const std::string & path) = 0;

    virtual std::string get_contours(const std::string & path) = 0;

    virtual std::string get_segments(const std::string & path) = 0;

    virtual std::string get_round_contours(const std::string & path) = 0;
};

}  // namespace opencv
