// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from opencv.djinni

#pragma once

#include <memory>
#include <string>

namespace opencv {

class Opencv {
public:
    virtual ~Opencv() {}

    static std::shared_ptr<Opencv> create();

    virtual std::string get_canny() = 0;

    virtual std::string get_threshold() = 0;

    virtual std::string get_lines() = 0;

    virtual std::string get_contours() = 0;

    virtual std::string get_segments() = 0;

    virtual std::string get_round_contours() = 0;
};

}  // namespace opencv
