// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from opencv.djinni

#pragma once

#include "djinni_support.hpp"
#include "opencv.hpp"

namespace djinni_generated {

class NativeOpencv final : ::djinni::JniInterface<::opencv::Opencv, NativeOpencv> {
public:
    using CppType = std::shared_ptr<::opencv::Opencv>;
    using CppOptType = std::shared_ptr<::opencv::Opencv>;
    using JniType = jobject;

    using Boxed = NativeOpencv;

    ~NativeOpencv();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeOpencv>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeOpencv>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeOpencv();
    friend ::djinni::JniClass<NativeOpencv>;
    friend ::djinni::JniInterface<::opencv::Opencv, NativeOpencv>;

};

}  // namespace djinni_generated
